### ISSUE TITLE
Linux D and V key appear to be in the wrong spot (Mod-DH)

### ISSUE THREAD

**Issue by stratacast** [DreymaR/BigBagKbdTrixXKB#8] opened 2018-04-05 20:34 UTC
I applied the the Mod-DH rules to my Dell XPS using the install-dreymar-xmod.sh script from the repository and I noticed that all was applied right except the D and the V keys were in the wrong location. I still suck at finding the config XKB files so I can't tell if it is a typo in the file, or an error in applying to my laptop, which is running Fedora 27 GNOME

**Comment by DreymaR** [comment] 2018-04-11 13:55
They aren't in the wrong position, but you need to also set a keyboard model with a CurlAngle mod. This depends on your keyboard type (ANSI vs ISO) and preferences in the case of ANSI (AngleZ vs others).

Sorry, but I couldn't make it perfectly modular.

**Comment by maxigit** [comment] 2020-12-03 11:36
I have a similar problem with the Curl-DH ergo mod.
As far as I understand D should be before V but this is not the case (D is in AB05 i.e.   the same column as B and G which contradict the Matrix/Ergo diagram on the Colemak mod-dh website.)

**Comment by DreymaR** [comment] 2020-12-03 12:37
Again, you have likely failed to set the keyboard Model component and only got the Layout component going for you. Please study the setxkb.sh script very closely, look inside it if you wish. And read the BigBag for XKB carefully.

**Comment by maxigit** [comment] 2020-12-03 12:55
I'm NOT using setxkb.sh, I'm using the installed layout (using the layout selector in Manjaro). The layout is called "English (Colemak[ed], Curl-DH ergo mod)". 

Also line 275 of `xkb/symbols/colemak` section "cmk_ed_dbg" D is explicitely mapped to  B (<AB05>). I understand this is done deliberately but you end up with the sequence `z x c v d` not `z x c d v` as it appears in all diagrams (with or withoult anglemode).

Is D not supposed to be below F (qwerty) in DH ergo mode ? What am I missing ?

**Comment by DreymaR** [comment] 2020-12-03 12:58
And I have to repeat myself: To use my implementation and get the right Curl-DH-Angle mod you HAVE TO SET THE KEYBOARD MODEL. Okay? Or edit the files.

Yes, the key is mapping D to B. Then the model moves it. That's the way this is made. Maybe I'll change it eventually since it's so hard to understand for you people.

**Comment by maxigit** [comment] 2020-12-03 13:15
I understand that using setxkb.sh will work. However for some reason, setxkb.sh doesn't work on my system.  Instead I'm using the layout installed by typing 

     bash install-dreymar.xmod.sh -o


I AM NOT usind setxkb.sh THEREFORE I CAN NOT set the keyboard model.

Maybe the problen the problem is not people not understanding things, maybe it is that the layout exported by `install-dreymar.xmod.sh` doesn't the set the keybord model.

Also, I don't want Angle model but Ergo as I have an ortholinear keyboard (but that is probably another problem).

Now, I've edited the file. I just thought you might interesting in the feedback : Selecting with GUI the Colemak DH ergo layout as D and V inversed. 
it's your stuff, you don't have to fix it indeed. I'm just telling.

**Comment by precondition** [comment] 2020-12-03 14:34
I don't know what DE you use, but you may be able to pick the right keyboard model graphically here, if I remember correctly:
![](http://i.imgur.com/JdaqCuh.png)

**Comment by DreymaR** [comment] 2020-12-03 15:04
The problem here may be that setting the keyboard model used to be easy and now in some distros it's hard. I'm not expecting anyone to use my setxkb script, that's not the point. But setting kbd model is quite different from Linux to Linux these days, and rather arcane in some of them. That's not how it was back when I first made my files! Ugh.

So yeah, I guess I really should find time to change this soon, to make things simpler. There have been several users who found it hard to both understand and perform.

**Comment by maxigit** [comment] 2020-12-03 15:05
I see. I didn't realize you meant model in the keyboard GUI.  However, I have an ortho-linear keyboard and setting the model to Angle doesn't really make sense (and just shift everything, removing the z).  So If I undertand well, there is no way to get [this]( http://colemakmods.github.io/mod-dh/gfx/colemak_dh_main_matrix.png) with the actual bag of tricks. Am I correct ?

**Comment by DreymaR** [comment] 2020-12-03 15:06
Yes, right now that's correct. Sorry, will fix eventually. For now, please edit the scan codes manually in the symbols/colemak file.

**Comment by maxigit** [comment] 2020-12-03 15:14
I understand now. Basically the "Angle" mode (shift zxcv to the left) is done by setting the keyboard model and should work with any layout, which makes sense. Am I correct ? However, the DH is then not implemented as a layout but as a curl variant of the angle mode (but not quite). So the actual implementation of DH is actually a mix betwen model and layout.
Well people (like me) expect just Colemak-DH to be yet another a layout (Colemak + mh loop and dvbg loop) nothing more and don't realize it is also a model.

**Comment by DreymaR** [comment] 2020-12-03 15:39
I know. One thing led to another and DH ended up being a chimera of layout and model. You see, I wanted the Extend+V mapping to follow the V key that separates from the ZXC keys in the DH mod (and in CurlAngle) but not in the Angle mod. Some might want to keep the Extend mapping in the old V position even though it no longer holds a V. And so it gets complicated.

And it got worse, because if you use the "CurlAngle" keyboard model and go back to a QWERTY layout the model will still swap your V and B keys unless you reset to the pc105 model at the same time! So yeah, I realize that this needs to be fixed now.

Thanks for the discussion!  ฅʕ •ᴥ•ʔฅ

**Comment by maxigit** [comment] 2020-12-03 16:42
I feel your pain. ;-)

**Comment by DreymaR** [comment] 2020-12-04 10:00
Hi! I just pushed a new commit that hopefully makes things easier for you. I removed the Curl keyboard models completely (although the setxkb.sh shortstrings still refer to them – which shouldn't affect you), and moved D inside V in the Curl(DH) layout itself instead. Hope that makes life better for you!

**Comment by maxigit** [comment] 2020-12-04 10:55
It works fine on my matrix keyboard ! Thank you very much :1st_place_medal:

**Closed** 2020-12-04 11:04 UTC
Labels: question
